version: '3'

services:
    slim:
        image: php:7-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
    db:
      image: postgres:11-alpine
      restart: always
      environment:
        POSTGRES_PASSWORD: example
      volumes:
        - db_data:/var/lib/postgresql/data

    adminer:
      image: adminer
      restart: always
      ports:
        - 8090:8080

volumes:
    logs:
    db_data:
